/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Section = IDL.Record({
  'title' : IDL.Text,
  'lyrics' : IDL.Vec(IDL.Text),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Type = IDL.Variant({
  'lent' : IDL.Null,
  'easter' : IDL.Null,
  'mass_songs' : IDL.Null,
  'advent' : IDL.Null,
  'marian_hymns' : IDL.Null,
  'general_devotion' : IDL.Null,
});
export const SongInput = IDL.Record({
  'title' : IDL.Text,
  'lyrics' : IDL.Vec(Section),
  'composer' : IDL.Text,
  'musicSheet' : IDL.Opt(ExternalBlob),
  'category' : Type,
});
export const SongId = IDL.Nat;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const Song = IDL.Record({
  'id' : SongId,
  'title' : IDL.Text,
  'lyrics' : IDL.Vec(Section),
  'createdAt' : Time,
  'composer' : IDL.Text,
  'updatedAt' : Time,
  'musicSheet' : IDL.Opt(ExternalBlob),
  'category' : Type,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addSong' : IDL.Func([SongInput], [SongId], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteSong' : IDL.Func([SongId], [], []),
  'getAllSongs' : IDL.Func([], [IDL.Vec(Song)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getSong' : IDL.Func([SongId], [Song], ['query']),
  'getSongsByCategory' : IDL.Func([Type], [IDL.Vec(Song)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'searchSongsByTitle' : IDL.Func([IDL.Text], [IDL.Vec(Song)], ['query']),
  'updateSong' : IDL.Func([SongId, SongInput], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Section = IDL.Record({
    'title' : IDL.Text,
    'lyrics' : IDL.Vec(IDL.Text),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Type = IDL.Variant({
    'lent' : IDL.Null,
    'easter' : IDL.Null,
    'mass_songs' : IDL.Null,
    'advent' : IDL.Null,
    'marian_hymns' : IDL.Null,
    'general_devotion' : IDL.Null,
  });
  const SongInput = IDL.Record({
    'title' : IDL.Text,
    'lyrics' : IDL.Vec(Section),
    'composer' : IDL.Text,
    'musicSheet' : IDL.Opt(ExternalBlob),
    'category' : Type,
  });
  const SongId = IDL.Nat;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const Song = IDL.Record({
    'id' : SongId,
    'title' : IDL.Text,
    'lyrics' : IDL.Vec(Section),
    'createdAt' : Time,
    'composer' : IDL.Text,
    'updatedAt' : Time,
    'musicSheet' : IDL.Opt(ExternalBlob),
    'category' : Type,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addSong' : IDL.Func([SongInput], [SongId], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteSong' : IDL.Func([SongId], [], []),
    'getAllSongs' : IDL.Func([], [IDL.Vec(Song)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getSong' : IDL.Func([SongId], [Song], ['query']),
    'getSongsByCategory' : IDL.Func([Type], [IDL.Vec(Song)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'searchSongsByTitle' : IDL.Func([IDL.Text], [IDL.Vec(Song)], ['query']),
    'updateSong' : IDL.Func([SongId, SongInput], [], []),
  });
};

export const init = ({ IDL }) => { return []; };