/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExternalBlob = Uint8Array;
export interface Section { 'title' : string, 'lyrics' : Array<string> }
export interface Song {
  'id' : SongId,
  'title' : string,
  'lyrics' : Array<Section>,
  'createdAt' : Time,
  'composer' : string,
  'updatedAt' : Time,
  'musicSheet' : [] | [ExternalBlob],
  'category' : Type,
}
export type SongId = bigint;
export interface SongInput {
  'title' : string,
  'lyrics' : Array<Section>,
  'composer' : string,
  'musicSheet' : [] | [ExternalBlob],
  'category' : Type,
}
export type Time = bigint;
export type Type = { 'lent' : null } |
  { 'easter' : null } |
  { 'mass_songs' : null } |
  { 'advent' : null } |
  { 'marian_hymns' : null } |
  { 'general_devotion' : null };
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addSong' : ActorMethod<[SongInput], SongId>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteSong' : ActorMethod<[SongId], undefined>,
  'getAllSongs' : ActorMethod<[], Array<Song>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getSong' : ActorMethod<[SongId], Song>,
  'getSongsByCategory' : ActorMethod<[Type], Array<Song>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'searchSongsByTitle' : ActorMethod<[string], Array<Song>>,
  'updateSong' : ActorMethod<[SongId, SongInput], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];