/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface MembershipApplication {
    id: MembershipId;
    name: string;
    submittedAt: Time;
    email: string;
    message: string;
    phone: string;
    parish: string;
}
export type Time = bigint;
export type SongId = bigint;
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export type MembershipId = bigint;
export interface MembershipApplicationInput {
    name: string;
    email: string;
    message: string;
    phone: string;
    parish: string;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export type NewsPostId = bigint;
export interface DevotionalPrayer {
    id: bigint;
    title: string;
    content: Array<Section>;
}
export interface NewsPost {
    id: NewsPostId;
    title: string;
    body: string;
    createdAt: Time;
    updatedAt: Time;
}
export interface DownloadItemInput {
    title: string;
    fileBlob: ExternalBlob;
    description: string;
}
export interface NewsPostInput {
    title: string;
    body: string;
}
export interface DownloadItem {
    id: DownloadItemId;
    title: string;
    createdAt: Time;
    fileBlob: ExternalBlob;
    description: string;
}
export interface Song {
    id: SongId;
    title: string;
    lyrics: Array<Section>;
    createdAt: Time;
    composer: string;
    updatedAt: Time;
    musicSheet?: ExternalBlob;
    category: Type;
}
export type DownloadItemId = bigint;
export interface SongInput {
    title: string;
    lyrics: Array<Section>;
    composer: string;
    musicSheet?: ExternalBlob;
    category: Type;
}
export interface Section {
    title: string;
    lyrics: Array<string>;
}
export interface UserProfile {
    name: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum Type {
    lent = "lent",
    easter = "easter",
    mass_songs = "mass_songs",
    advent = "advent",
    marian_hymns = "marian_hymns",
    general_devotion = "general_devotion"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addDownloadItem(downloadItemInput: DownloadItemInput): Promise<DownloadItemId>;
    addNewsPost(newsPostInput: NewsPostInput): Promise<NewsPostId>;
    addSong(songInput: SongInput): Promise<SongId>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    deleteDownloadItem(id: DownloadItemId): Promise<void>;
    deleteMembershipApplication(id: MembershipId): Promise<void>;
    deleteNewsPost(id: NewsPostId): Promise<void>;
    deleteSong(id: SongId): Promise<void>;
    getAllDevotionalPrayers(): Promise<Array<DevotionalPrayer>>;
    getAllDownloadItems(): Promise<Array<DownloadItem>>;
    getAllMembershipApplications(): Promise<Array<MembershipApplication>>;
    getAllNewsPosts(): Promise<Array<NewsPost>>;
    getAllSongs(): Promise<Array<Song>>;
    getByCategory(): Promise<{
        lent: Array<Song>;
        easter: Array<Song>;
        mass_songs: Array<Song>;
        advent: Array<Song>;
        marian_hymns: Array<Song>;
        general_devotion: Array<Song>;
    }>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDevotionalPrayer(id: bigint): Promise<DevotionalPrayer>;
    getDownloadItem(id: DownloadItemId): Promise<DownloadItem>;
    getNewsPost(id: NewsPostId): Promise<NewsPost>;
    getSong(id: SongId): Promise<Song>;
    getSongsByCategory(category: Type): Promise<Array<Song>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    searchDevotionalPrayers(searchTerm: string): Promise<Array<DevotionalPrayer>>;
    searchMembershipApplications(searchTerm: string): Promise<Array<MembershipApplication>>;
    searchSongsByTitle(searchTerm: string): Promise<Array<Song>>;
    submitMembershipApplication(applicationInput: MembershipApplicationInput): Promise<MembershipId>;
    updateNewsPost(id: NewsPostId, newsPostInput: NewsPostInput): Promise<void>;
    updateSong(id: SongId, songInput: SongInput): Promise<void>;
}
import type { DownloadItem as _DownloadItem, DownloadItemId as _DownloadItemId, DownloadItemInput as _DownloadItemInput, ExternalBlob as _ExternalBlob, Section as _Section, Song as _Song, SongId as _SongId, SongInput as _SongInput, Time as _Time, Type as _Type, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addDownloadItem(arg0: DownloadItemInput): Promise<DownloadItemId> {
        if (this.processError) {
            try {
                const result = await this.actor.addDownloadItem(await to_candid_DownloadItemInput_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addDownloadItem(await to_candid_DownloadItemInput_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addNewsPost(arg0: NewsPostInput): Promise<NewsPostId> {
        if (this.processError) {
            try {
                const result = await this.actor.addNewsPost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addNewsPost(arg0);
            return result;
        }
    }
    async addSong(arg0: SongInput): Promise<SongId> {
        if (this.processError) {
            try {
                const result = await this.actor.addSong(await to_candid_SongInput_n11(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSong(await to_candid_SongInput_n11(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n15(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n15(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteDownloadItem(arg0: DownloadItemId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteDownloadItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteDownloadItem(arg0);
            return result;
        }
    }
    async deleteMembershipApplication(arg0: MembershipId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMembershipApplication(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMembershipApplication(arg0);
            return result;
        }
    }
    async deleteNewsPost(arg0: NewsPostId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteNewsPost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteNewsPost(arg0);
            return result;
        }
    }
    async deleteSong(arg0: SongId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSong(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSong(arg0);
            return result;
        }
    }
    async getAllDevotionalPrayers(): Promise<Array<DevotionalPrayer>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDevotionalPrayers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDevotionalPrayers();
            return result;
        }
    }
    async getAllDownloadItems(): Promise<Array<DownloadItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDownloadItems();
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDownloadItems();
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllMembershipApplications(): Promise<Array<MembershipApplication>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMembershipApplications();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMembershipApplications();
            return result;
        }
    }
    async getAllNewsPosts(): Promise<Array<NewsPost>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllNewsPosts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllNewsPosts();
            return result;
        }
    }
    async getAllSongs(): Promise<Array<Song>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSongs();
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSongs();
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getByCategory(): Promise<{
        lent: Array<Song>;
        easter: Array<Song>;
        mass_songs: Array<Song>;
        advent: Array<Song>;
        marian_hymns: Array<Song>;
        general_devotion: Array<Song>;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getByCategory();
                return from_candid_record_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getByCategory();
            return from_candid_record_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDevotionalPrayer(arg0: bigint): Promise<DevotionalPrayer> {
        if (this.processError) {
            try {
                const result = await this.actor.getDevotionalPrayer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDevotionalPrayer(arg0);
            return result;
        }
    }
    async getDownloadItem(arg0: DownloadItemId): Promise<DownloadItem> {
        if (this.processError) {
            try {
                const result = await this.actor.getDownloadItem(arg0);
                return from_candid_DownloadItem_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDownloadItem(arg0);
            return from_candid_DownloadItem_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNewsPost(arg0: NewsPostId): Promise<NewsPost> {
        if (this.processError) {
            try {
                const result = await this.actor.getNewsPost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNewsPost(arg0);
            return result;
        }
    }
    async getSong(arg0: SongId): Promise<Song> {
        if (this.processError) {
            try {
                const result = await this.actor.getSong(arg0);
                return from_candid_Song_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSong(arg0);
            return from_candid_Song_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSongsByCategory(arg0: Type): Promise<Array<Song>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSongsByCategory(to_candid_Type_n13(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSongsByCategory(to_candid_Type_n13(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async searchDevotionalPrayers(arg0: string): Promise<Array<DevotionalPrayer>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchDevotionalPrayers(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchDevotionalPrayers(arg0);
            return result;
        }
    }
    async searchMembershipApplications(arg0: string): Promise<Array<MembershipApplication>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchMembershipApplications(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchMembershipApplications(arg0);
            return result;
        }
    }
    async searchSongsByTitle(arg0: string): Promise<Array<Song>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchSongsByTitle(arg0);
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchSongsByTitle(arg0);
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitMembershipApplication(arg0: MembershipApplicationInput): Promise<MembershipId> {
        if (this.processError) {
            try {
                const result = await this.actor.submitMembershipApplication(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitMembershipApplication(arg0);
            return result;
        }
    }
    async updateNewsPost(arg0: NewsPostId, arg1: NewsPostInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateNewsPost(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateNewsPost(arg0, arg1);
            return result;
        }
    }
    async updateSong(arg0: SongId, arg1: SongInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSong(arg0, await to_candid_SongInput_n11(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSong(arg0, await to_candid_SongInput_n11(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
async function from_candid_DownloadItem_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DownloadItem): Promise<DownloadItem> {
    return await from_candid_record_n19(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
async function from_candid_Song_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Song): Promise<Song> {
    return await from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_Type_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Type): Type {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
async function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n20(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _DownloadItemId;
    title: string;
    createdAt: _Time;
    fileBlob: _ExternalBlob;
    description: string;
}): Promise<{
    id: DownloadItemId;
    title: string;
    createdAt: Time;
    fileBlob: ExternalBlob;
    description: string;
}> {
    return {
        id: value.id,
        title: value.title,
        createdAt: value.createdAt,
        fileBlob: await from_candid_ExternalBlob_n20(_uploadFile, _downloadFile, value.fileBlob),
        description: value.description
    };
}
async function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _SongId;
    title: string;
    lyrics: Array<_Section>;
    createdAt: _Time;
    composer: string;
    updatedAt: _Time;
    musicSheet: [] | [_ExternalBlob];
    category: _Type;
}): Promise<{
    id: SongId;
    title: string;
    lyrics: Array<Section>;
    createdAt: Time;
    composer: string;
    updatedAt: Time;
    musicSheet?: ExternalBlob;
    category: Type;
}> {
    return {
        id: value.id,
        title: value.title,
        lyrics: value.lyrics,
        createdAt: value.createdAt,
        composer: value.composer,
        updatedAt: value.updatedAt,
        musicSheet: record_opt_to_undefined(await from_candid_opt_n24(_uploadFile, _downloadFile, value.musicSheet)),
        category: from_candid_Type_n25(_uploadFile, _downloadFile, value.category)
    };
}
async function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    lent: Array<_Song>;
    easter: Array<_Song>;
    mass_songs: Array<_Song>;
    advent: Array<_Song>;
    marian_hymns: Array<_Song>;
    general_devotion: Array<_Song>;
}): Promise<{
    lent: Array<Song>;
    easter: Array<Song>;
    mass_songs: Array<Song>;
    advent: Array<Song>;
    marian_hymns: Array<Song>;
    general_devotion: Array<Song>;
}> {
    return {
        lent: await from_candid_vec_n21(_uploadFile, _downloadFile, value.lent),
        easter: await from_candid_vec_n21(_uploadFile, _downloadFile, value.easter),
        mass_songs: await from_candid_vec_n21(_uploadFile, _downloadFile, value.mass_songs),
        advent: await from_candid_vec_n21(_uploadFile, _downloadFile, value.advent),
        marian_hymns: await from_candid_vec_n21(_uploadFile, _downloadFile, value.marian_hymns),
        general_devotion: await from_candid_vec_n21(_uploadFile, _downloadFile, value.general_devotion)
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    lent: null;
} | {
    easter: null;
} | {
    mass_songs: null;
} | {
    advent: null;
} | {
    marian_hymns: null;
} | {
    general_devotion: null;
}): Type {
    return "lent" in value ? Type.lent : "easter" in value ? Type.easter : "mass_songs" in value ? Type.mass_songs : "advent" in value ? Type.advent : "marian_hymns" in value ? Type.marian_hymns : "general_devotion" in value ? Type.general_devotion : value;
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
async function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DownloadItem>): Promise<Array<DownloadItem>> {
    return await Promise.all(value.map(async (x)=>await from_candid_DownloadItem_n18(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Song>): Promise<Array<Song>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Song_n22(_uploadFile, _downloadFile, x)));
}
async function to_candid_DownloadItemInput_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DownloadItemInput): Promise<_DownloadItemInput> {
    return await to_candid_record_n9(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
async function to_candid_SongInput_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SongInput): Promise<_SongInput> {
    return await to_candid_record_n12(_uploadFile, _downloadFile, value);
}
function to_candid_Type_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Type): _Type {
    return to_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
async function to_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    lyrics: Array<Section>;
    composer: string;
    musicSheet?: ExternalBlob;
    category: Type;
}): Promise<{
    title: string;
    lyrics: Array<_Section>;
    composer: string;
    musicSheet: [] | [_ExternalBlob];
    category: _Type;
}> {
    return {
        title: value.title,
        lyrics: value.lyrics,
        composer: value.composer,
        musicSheet: value.musicSheet ? candid_some(await to_candid_ExternalBlob_n10(_uploadFile, _downloadFile, value.musicSheet)) : candid_none(),
        category: to_candid_Type_n13(_uploadFile, _downloadFile, value.category)
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
async function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    fileBlob: ExternalBlob;
    description: string;
}): Promise<{
    title: string;
    fileBlob: _ExternalBlob;
    description: string;
}> {
    return {
        title: value.title,
        fileBlob: await to_candid_ExternalBlob_n10(_uploadFile, _downloadFile, value.fileBlob),
        description: value.description
    };
}
function to_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Type): {
    lent: null;
} | {
    easter: null;
} | {
    mass_songs: null;
} | {
    advent: null;
} | {
    marian_hymns: null;
} | {
    general_devotion: null;
} {
    return value == Type.lent ? {
        lent: null
    } : value == Type.easter ? {
        easter: null
    } : value == Type.mass_songs ? {
        mass_songs: null
    } : value == Type.advent ? {
        advent: null
    } : value == Type.marian_hymns ? {
        marian_hymns: null
    } : value == Type.general_devotion ? {
        general_devotion: null
    } : value;
}
function to_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
